-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaMsefmAQkoUKxw+/
iUGdOlUjoN9FNUvQM7bH/69ivsqgCgYIKoZIzj0DAQehRANCAASz98PSHgQXPSpg
3Cldkb+XDpmJfc4f728y++0Y+8TCeN1Agb1LZY/gc4k9rkH4TIQffqNV4yz+loxJ
ChsvtCUV
-----END PRIVATE KEY-----