name: upaychat
description: UpayChat

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^2.0.7
  http: ^0.13.3
  fluttertoast: ^8.0.8
  image_picker: ^0.8.3+3
  image_cropper: ^1.4.1
  connectivity: ^3.0.6
  flutter_spinkit: ^5.1.0
  pin_input_text_field: ^4.1.0
  timeago: ^3.1.0
  international_phone_input: ^1.0.4
  dotted_line: ^3.0.0
  eventhandler: ^1.0.4
  flutter_credit_card: ^2.0.0
  url_launcher: ^6.0.9
  firebase_messaging: ^10.0.6
  flutter_local_notifications: ^8.1.1+2
  intl: ^0.17.0
  flutter_paystack: ^1.0.5+1
  contacts_service: ^0.6.1
  permission_handler: ^8.1.4+2
  firebase_auth: ^3.1.0
  badges: ^2.0.1
  flutter_slidable: ^0.6.0
  firebase_database: ^8.0.0
  pin_code_fields: ^7.3.0
  pdf: ^3.6.0
  path_provider: ^2.0.4
  touchable_opacity: ^1.2.0
  file_picker: ^4.1.4
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_vector_icons: ^1.0.0
  cupertino_date_textbox: ^1.0.1
  flutter_image_compress: ^1.1.0
  gallery_saver: ^2.3.2
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: false
  android: "launcher_icon"
  image_path: "assets/logo.png"    #for android
#  image_path: "assets/ios_logo.jpg"    #for ios

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/ios_logo.jpg
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Doomsday
      fonts:
        - asset: fonts/LayarBahtera Doomsday.ttf
        - asset: fonts/LayarBahtera Doomsday Light.ttf
        - asset: fonts/LayarBahtera Doomsday Extended.ttf
        - asset: fonts/LayarBahtera Doomsday Extended Light.ttf
        - asset: fonts/LayarBahtera Doomsday Extended Bold.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed Light.ttf
        - asset: fonts/LayarBahtera Doomsday Condensed Bold.ttf
        - asset: fonts/LayarBahtera Doomsday Bold.ttf
        - asset: fonts/Layar Bahtera Doomsday Light Italic.ttf
        - asset: fonts/Layar Bahtera Doomsday Italic.ttf
        - asset: fonts/Layar Bahtera Doomsday Bold Italic.ttf
